### ISSUE TITLE
Failed compiling src

### ISSUE THREAD

**Issue by patricia241** [KCL-Planning/DiNo#9]
`In file included from pddl+.yacc:1423:
lex.yy.cc: In member function ‘virtual int yyFlexLexer::yylex()’:
lex.yy.cc:1169:18: error: no match for ‘operator=’ (operand types are ‘std::istream’ {aka ‘std::basic_istream<char>’} and ‘std::istream*’ {aka ‘std::basic_istream<char>*’})
 1169 |    yyin = & std::cin;
      |                  ^~~
In file included from /usr/include/c++/9/fstream:38,
                 from pddl+.yacc:45:
/usr/include/c++/9/istream:625:7: note: candidate: ‘std::basic_istream<_CharT, _Traits>& std::basic_istream<_CharT, _Traits>::operator=(std::basic_istream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]’
  625 |       operator=(basic_istream&& __rhs)
      |       ^~~~~~~~
/usr/include/c++/9/istream:625:33: note:   no known conversion for argument 1 from ‘std::istream*’ {aka ‘std::basic_istream<char>*’} to ‘std::basic_istream<char>&&’
  625 |       operator=(basic_istream&& __rhs)
      |                 ~~~~~~~~~~~~~~~~^~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc:1172:19: error: no match for ‘operator=’ (operand types are ‘std::ostream’ {aka ‘std::basic_ostream<char>’} and ‘std::ostream*’ {aka ‘std::basic_ostream<char>*’})
 1172 |    yyout = & std::cout;
      |                   ^~~~
In file included from /usr/include/c++/9/istream:39,
                 from /usr/include/c++/9/fstream:38,
                 from pddl+.yacc:45:
/usr/include/c++/9/ostream:408:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator=(std::basic_ostream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]’
  408 |       operator=(basic_ostream&& __rhs)
      |       ^~~~~~~~
/usr/include/c++/9/ostream:408:33: note:   no known conversion for argument 1 from ‘std::ostream*’ {aka ‘std::basic_ostream<char>*’} to ‘std::basic_ostream<char>&&’
  408 |       operator=(basic_ostream&& __rhs)
      |                 ~~~~~~~~~~~~~~~~^~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc:1816:46: error: cannot convert ‘std::istream’ {aka ‘std::basic_istream<char>’} to ‘std::istream*’ {aka ‘std::basic_istream<char>*’} in assignment
 1816 |    YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
      |                                              ^~~~
      |                                              |
      |                                              std::istream {aka std::basic_istream<char>}
lex.yy.cc: In constructor ‘yyFlexLexer::yyFlexLexer(std::istream*, std::ostream*)’:
lex.yy.cc:1926:75: error: ‘std::basic_istream<_CharT, _Traits>::basic_istream() [with _CharT = char; _Traits = std::char_traits<char>]’ is protected within this context
 1926 | yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
      |                                                                           ^
In file included from /usr/include/c++/9/fstream:38,
                 from pddl+.yacc:45:
/usr/include/c++/9/istream:606:7: note: declared protected here
  606 |       basic_istream()
      |       ^~~~~~~~~~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc:1926:75: error: ‘std::basic_ostream<_CharT, _Traits>::basic_ostream() [with _CharT = char; _Traits = std::char_traits<char>]’ is protected within this context
 1926 | yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
      |                                                                           ^
In file included from /usr/include/c++/9/istream:39,
                 from /usr/include/c++/9/fstream:38,
                 from pddl+.yacc:45:
/usr/include/c++/9/ostream:390:7: note: declared protected here
  390 |       basic_ostream()
      |       ^~~~~~~~~~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc:1928:9: error: no match for ‘operator=’ (operand types are ‘std::istream’ {aka ‘std::basic_istream<char>’} and ‘std::istream*’ {aka ‘std::basic_istream<char>*’})
 1928 |  yyin = arg_yyin;
      |         ^~~~~~~~
In file included from /usr/include/c++/9/fstream:38,
                 from pddl+.yacc:45:
/usr/include/c++/9/istream:625:7: note: candidate: ‘std::basic_istream<_CharT, _Traits>& std::basic_istream<_CharT, _Traits>::operator=(std::basic_istream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]’
  625 |       operator=(basic_istream&& __rhs)
      |       ^~~~~~~~
/usr/include/c++/9/istream:625:33: note:   no known conversion for argument 1 from ‘std::istream*’ {aka ‘std::basic_istream<char>*’} to ‘std::basic_istream<char>&&’
  625 |       operator=(basic_istream&& __rhs)
      |                 ~~~~~~~~~~~~~~~~^~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc:1929:10: error: no match for ‘operator=’ (operand types are ‘std::ostream’ {aka ‘std::basic_ostream<char>’} and ‘std::ostream*’ {aka ‘std::basic_ostream<char>*’})
 1929 |  yyout = arg_yyout;
      |          ^~~~~~~~~
In file included from /usr/include/c++/9/istream:39,
                 from /usr/include/c++/9/fstream:38,
                 from pddl+.yacc:45:
/usr/include/c++/9/ostream:408:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator=(std::basic_ostream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]’
  408 |       operator=(basic_ostream&& __rhs)
      |       ^~~~~~~~
/usr/include/c++/9/ostream:408:33: note:   no known conversion for argument 1 from ‘std::ostream*’ {aka ‘std::basic_ostream<char>*’} to ‘std::basic_ostream<char>&&’
  408 |       operator=(basic_ostream&& __rhs)
      |                 ~~~~~~~~~~~~~~~~^~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc: In member function ‘virtual void yyFlexLexer::switch_streams(std::istream*, std::ostream*)’:
lex.yy.cc:1975:11: error: no match for ‘operator=’ (operand types are ‘std::ostream’ {aka ‘std::basic_ostream<char>’} and ‘std::ostream*’ {aka ‘std::basic_ostream<char>*’})
 1975 |   yyout = new_out;
      |           ^~~~~~~
In file included from /usr/include/c++/9/istream:39,
                 from /usr/include/c++/9/fstream:38,
                 from pddl+.yacc:45:
/usr/include/c++/9/ostream:408:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>& std::basic_ostream<_CharT, _Traits>::operator=(std::basic_ostream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]’
  408 |       operator=(basic_ostream&& __rhs)
      |       ^~~~~~~~
/usr/include/c++/9/ostream:408:33: note:   no known conversion for argument 1 from ‘std::ostream*’ {aka ‘std::basic_ostream<char>*’} to ‘std::basic_ostream<char>&&’
  408 |       operator=(basic_ostream&& __rhs)
      |                 ~~~~~~~~~~~~~~~~^~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc: In member function ‘virtual int yyFlexLexer::LexerInput(char*, int)’:
lex.yy.cc:1984:11: error: base operand of ‘->’ has non-pointer type ‘std::istream’ {aka ‘std::basic_istream<char>’}
 1984 |  if ( yyin->eof() || yyin->fail() )
      |           ^~
lex.yy.cc:1984:26: error: base operand of ‘->’ has non-pointer type ‘std::istream’ {aka ‘std::basic_istream<char>’}
 1984 |  if ( yyin->eof() || yyin->fail() )
      |                          ^~
lex.yy.cc:1988:6: error: base operand of ‘->’ has non-pointer type ‘std::istream’ {aka ‘std::basic_istream<char>’}
 1988 |  yyin->get( buf[0] );
      |      ^~
lex.yy.cc:1990:11: error: base operand of ‘->’ has non-pointer type ‘std::istream’ {aka ‘std::basic_istream<char>’}
 1990 |  if ( yyin->eof() )
      |           ^~
lex.yy.cc:1993:11: error: base operand of ‘->’ has non-pointer type ‘std::istream’ {aka ‘std::basic_istream<char>’}
 1993 |  if ( yyin->bad() )
      |           ^~
lex.yy.cc: In member function ‘virtual void yyFlexLexer::LexerOutput(const char*, int)’:
lex.yy.cc:2010:14: error: base operand of ‘->’ has non-pointer type ‘std::ostream’ {aka ‘std::basic_ostream<char>’}
 2010 |  (void) yyout->write( buf, size );
      |              ^~
lex.yy.cc: In member function ‘virtual void yyFlexLexer::yyrestart(std::istream*)’:
lex.yy.cc:2330:37: error: cannot convert ‘std::istream*’ {aka ‘std::basic_istream<char>*’} to ‘std::istream&’ {aka ‘std::basic_istream<char>&’}
 2330 |  yy_init_buffer( YY_CURRENT_BUFFER, input_file );
      |                                     ^~~~~~~~~~
      |                                     |
      |                                     std::istream* {aka std::basic_istream<char>*}
In file included from lex.yy.cc:322,
                 from pddl+.yacc:1423:
/usr/include/FlexLexer.h:156:58: note:   initializing argument 2 of ‘void yyFlexLexer::yy_init_buffer(yy_buffer_state*, std::istream&)’
  156 |   void yy_init_buffer( yy_buffer_state* b, std::istream& s );
      |                                            ~~~~~~~~~~~~~~^
In file included from pddl+.yacc:1423:
lex.yy.cc: In member function ‘void yyFlexLexer::yy_load_buffer_state()’:
lex.yy.cc:2373:35: error: no match for ‘operator=’ (operand types are ‘std::istream’ {aka ‘std::basic_istream<char>’} and ‘std::istream*’ {aka ‘std::basic_istream<char>*’})
 2373 |  yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
      |                                   ^~~~~~~~~~~~~
In file included from /usr/include/c++/9/fstream:38,
                 from pddl+.yacc:45:
/usr/include/c++/9/istream:625:7: note: candidate: ‘std::basic_istream<_CharT, _Traits>& std::basic_istream<_CharT, _Traits>::operator=(std::basic_istream<_CharT, _Traits>&&) [with _CharT = char; _Traits = std::char_traits<char>]’
  625 |       operator=(basic_istream&& __rhs)
      |       ^~~~~~~~
/usr/include/c++/9/istream:625:33: note:   no known conversion for argument 1 from ‘std::istream*’ {aka ‘std::basic_istream<char>*’} to ‘std::basic_istream<char>&&’
  625 |       operator=(basic_istream&& __rhs)
      |                 ~~~~~~~~~~~~~~~~^~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc: In member function ‘virtual yy_buffer_state* yyFlexLexer::yy_create_buffer(std::istream*, int)’:
lex.yy.cc:2402:21: error: cannot convert ‘std::istream*’ {aka ‘std::basic_istream<char>*’} to ‘std::istream&’ {aka ‘std::basic_istream<char>&’}
 2402 |  yy_init_buffer( b, file );
      |                     ^~~~
      |                     |
      |                     std::istream* {aka std::basic_istream<char>*}
In file included from lex.yy.cc:322,
                 from pddl+.yacc:1423:
/usr/include/FlexLexer.h:156:58: note:   initializing argument 2 of ‘void yyFlexLexer::yy_init_buffer(yy_buffer_state*, std::istream&)’
  156 |   void yy_init_buffer( yy_buffer_state* b, std::istream& s );
      |                                            ~~~~~~~~~~~~~~^
In file included from pddl+.yacc:1423:
lex.yy.cc: At global scope:
lex.yy.cc:22:25: error: no declaration matches ‘void yyFlexLexer::yy_init_buffer(YY_BUFFER_STATE, std::istream*)’
   22 |     #define yyFlexLexer yyFlexLexer
      |                         ^~~~~~~~~~~
lex.yy.cc:2432:10: note: in expansion of macro ‘yyFlexLexer’
 2432 |     void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )
      |          ^~~~~~~~~~~
In file included from lex.yy.cc:322,
                 from pddl+.yacc:1423:
/usr/include/FlexLexer.h:156:8: note: candidate is: ‘void yyFlexLexer::yy_init_buffer(yy_buffer_state*, std::istream&)’
  156 |   void yy_init_buffer( yy_buffer_state* b, std::istream& s );
      |        ^~~~~~~~~~~~~~
In file included from pddl+.yacc:1423:
lex.yy.cc:22:25: note: ‘class yyFlexLexer’ defined here
   22 |     #define yyFlexLexer yyFlexLexer
      |                         ^~~~~~~~~~~
make[1]: *** [Makefile:27: pddl+.o] Error 1
make[1]: se sale del directorio '/home/patri/DiNo/src/DiNo_parser'
make: *** [Makefile:7: pddl2upm] Error 2
`
I have this errors. I'm working in Ubuntu 20.04. How I can solve it?
